config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "posts#new"
  get '/:code', to: 'links#show'
  post '/links', to: 'links#create'

  resources :posts, only: :show
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # get '/s/:slug', to: 'links#show', as: :short
  # get '/s/:slug', to: 'links#slug'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/link.rb
class Link < ApplicationRecord
  validates_presence_of :code, :long_url
  validate :long_url_format

  def long_url_format
    uri = URI.parse(long_url || "")
    if uri.host.nil?
      errors.add(:long_url, 'Invalid URL format')
    end
    # rescue URI::InvalidURIError => e
  end

  def recent_shortened_url
    "http://localhost:3000/#{Link.last.code}"
  end

  def shortened_url
    "http://localhost:3000/#{code}"
  end

  def custom_url
    random = sprintf "%04d", rand( - 9999)
    "http://CustomUrl.com/#{random}"
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable,  and :omniauthable
  devise :database_authenticatable, :registerable, :trackable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_up_path_for(resource)
    after_sign_in_path_for(resource) if is_navigational_format?
  end

end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  def show #table show
    link = Link.find_by(code: params[:code])
    redirect_to link.long_url, allow_other_host: true
  end

  def create
    shortener = Shortener.new(link_params[:long_url])
    @link = shortener.generate_short_link
    if @link.save
      redirect_back(fallback_location: root_path)
    else
      not_found
    end
  end

  private

  def link_params
    params.require(:link).permit(:long_url)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  require 'csv'

  def new
    @link = Link.new
    @links = Link.all

      respond_to do |format|
        format.html
        format.csv {
          csv_string = CSV.generate do |csv|
            csv << [User.human_attribute_name(:email), Link.human_attribute_name(:id), Link.human_attribute_name(:code), Link.human_attribute_name(:long_url), Link.human_attribute_name(:click), Link.human_attribute_name(:created_at)]
            @links.each do |p|
              csv << [p.user.email, p.id, p.code, p.long_url, p.click, p.created_at]
            end
          end
          send_data csv_string, :filename => "links-#{Time.now.to_s(:number)}.csv"
        }
      end
    end

  def show #Click Show
    @link = Link.find(params[:id])
    @link.update_attribute(:click, @link.click + 1)
    redirect_to @link.long_url, allow_other_host: true
  end

  def destroy
    @link = Link.find_by(params[:id])
    @link.destroy
    redirect_to post_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/new.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">URL Shortener</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to "Sign-in", user_session_path, class: "nav-link", style: "background: none; border: none; color: green" unless user_signed_in? %>
            <%= button_to 'Sign-Out', destroy_user_session_path, class: "nav-link", style: "background: none; border: none; color: red", method: :delete if user_signed_in? %>
          </li>

          <li class="nav-item ">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true"><%= "Welcome #{current_user.email}" if current_user %></a>
          </li>
        </ul>
        <%= form_with model: @link, class: "d-flex", remote: true do |f| %>
          <%= f.text_field :long_url, class: "form-control me-2", style: "width: 800px" , placeholder: "Enter URL here" %>
          <%= f.text_field :alias, class: "form-control me-2", style: "width: 200px",  placeholder: "Enter Alias here" %>
          <%= f.submit 'Generate', class: "btn btn-outline-success" %>
        <% end %>
      </div>
    </div>
  </nav>
  <div>
  <h4 data-controller='clipboard' class="container alert alert-success text-center">
    <button class="btn btn-outline-dark w-25" data-action="click->clipboard#copy">COPY</button>
    <span data-clipboard-target="source"><%= @link.recent_shortened_url %></span>
  </h4>
  </div>
  <h1 class="text-center">List of URL</h1>  <%= link_to "Export CSV", links_path(:format => :csv), :class => "btn btn-default" %>
  <p class="notice" style="color: green"><%= notice %></p>
  <p class="alert" style="color: red"><%= alert %></p>
</header>

<div>
  <%if user_signed_in? %>
  <table class="table text-center ">
    <thead >
    <tr>
      <th>Code</th>
      <th>Default URL</th>
      <th>Shortened URL</th>
      <th>Total Click Counts</th>
      <th colspan="2">User Status</th>
      <th>Actions</th>
    </tr>
    </thead>
    <% @links.each do |link| %>
    <tbody>
    <tr>
      <td><%= link.code %></td>
      <td><%= link.long_url %></td>
      <td><%= link_to link.shortened_url, post_path(link), target: '_blank' %></td>
      <td><%= link.click %></td>
      <td><%= request.user_agent.truncate(50) %></td>
      <td><%= request.remote_ip %></td>
      <td></td>
      <td><%= button_to 'Delete', post_path(link), method: :delete, class: "btn btn-danger" %></td>

    </tr>
    </tbody>
      <% end %>
  </table>
<% end %>
</div>